[[redirects]]
  from = "/play/:id"
  to = "/viewer.html?id=:id"
  status = 200
  force = true

[[headers]]
  for = "/ads.txt"
  [headers.values]
    "Content-Type" = "text/plain"

[[headers]]
  for = "/viewer.html"
  [headers.values]
    Cache-Control = "public, max-age=3600"
    X-Frame-Options = "SAMEORIGIN"
